name: "End"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  terraform:
    name: 'Pipeline'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./pipeline
    env:
      TARGET_BRANCH: ${{ github.event_name == 'pull_request' && github.base_ref || github.ref_name }}
    
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Print variables'
        id: env
        run: |
          echo "event_name=${{ github.event_name }}" >> $GITHUB_OUTPUT
          echo "ref_name=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          echo "base_ref=${{ github.base_ref }}" >> $GITHUB_OUTPUT

      - name: 'Run deploy script'
        run: |
          chmod +x ./deploy_pipeline.sh
          ./deploy_pipeline.sh
        env:
          EVENT_NAME: ${{ steps.env.outputs.event_name }}
          REF_NAME: ${{ steps.env.outputs.ref_name }}
          BASE_NAME: ${{ steps.env.outputs.base_ref }}
          TARGET_BRANCH: ${{ github.event_name == 'pull_request' && github.base_ref || github.ref_name }}