name: "Initial"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infra
    env:
      TARGET_BRANCH: ${{ github.event_name == 'pull_request' && github.base_ref || github.ref_name }}
    
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Set Outputs (Old Way with EOF)'
        id: set_outputs
        run: |
          cat << 'EOF' > dummy_terraform.json
          {
            "function_build_sa_email": {
              "sensitive": false,
              "type": "string",
              "value": "cuspfe-sa-embase-function-b@prj-pfe-data-pfrontiers-dev01.iam.gserviceaccount.com"
            },
            "function_sa_email": {
              "sensitive": false,
              "type": "string",
              "value": "cuspfe-sa-embase-function@prj-pfe-data-pfrontiers-dev01.iam.gserviceaccount.com"
            }
          }
          EOF

          echo "output_vars=$(cat dummy_terraform.json)" >> $GITHUB_OUTPUT
      
      - name: 'Run deploy script'
        run: |
          chmod +x ./deploy_infra.sh
          ./deploy_infra.sh
        env:
          OUTPUT_VARS: ${{ steps.set_outputs.outputs.output_vars }}



